branch: develop
schedule: "every week on wednesday"
search: False

requirements:
  - requirements.txt:
      update: all
      pin: True
  - requirements_2.7.txt:
      update: insecure
      pin: True
